### PR TITLE
Fixed #358 - configuration on Disk from clean folder

### LINKED ISSUE #358: Running server with Simple Disk storage seems always to use volatile memory
### Context / Scenario

I configured the Server with this section for services. As you can see I uses simple queue on disk, file storage on disk and vector memory on disk. The server starts and works perfectly but all the services uses Volatile File system, not using file system on disk.

```json
 "Services": {
      "SimpleQueues": {
        "Directory": "c:\\temp\\km\\queue"
      },
      "SimpleFileStorage": {
        "Directory": "c:\\temp\\km\\storage"
      },
      "OpenAI": {
        "TextModel": "gpt-3.5-turbo-16k",
        "EmbeddingModel": "text-embedding-ada-002",
        "APIKey": "my-api-key",
        "OrgId": "",
        "MaxRetries": 10
      },
      "SimpleVectorDb": {
        "Directory": "c:\\temp\\km\\vector"
      }
    }
```

### Question

What is wrong in the configuration above? I generated with dotnet run config and it seems to be correct, but nevertheless no data is persisted on disk.

Also if I download the project in a fresh folder or delete all non source controlled file `git clean -xdf` when I run dotnet run setup I got an error because it does not find the application.development.json.

### PR DESCRIPTION
**Pull request by alkampfergit**
## Motivation and Context (Why the change? What's the scenario?)

When you download the project in a fresh folder, running `dotnet run setup` in the service folder throws an error because development.json file does not exists.

Also if you configure using Disk storage (not for production but useful for testing) actually it uses volatile storage and does not persist anytying on disk.

it will fix #358

## High level description (Approach, Design)

I've simply restored the generation of basic development file if not exists, also fixed configuration using "disk" storage type instead of "volatile"

### CODE REVIEW

**Comment by alkampfergit** [comment]
This will fix #358

File: tools/InteractiveSetup/Main.cs [hunk 1]
```diff
@@ -622,12 +622,13 @@ private static void SimpleQueuesSetup()
             config = new Dictionary<string, object>
             {
                 { "Directory", "" },
-                { "StorageType", "Volatile" }
```
Comment (dluc) [inline tools/InteractiveSetup/Main.cs:625]: Volatile is default mode when not specified, it's on purpose. We can extend the setup wizard to ask, but we won't change the default because it would impact other things.

File: service/Core/Handlers/DependencyInjection.cs [hunk 2]
```diff
@@ -103,8 +103,7 @@ public static IServiceCollection AddDefaultHandlersAsHostedServices(this IServic
         // Build generic type: HandlerAsAHostedService<THandler>
         Type handlerAsAHostedServiceTHandler = typeof(HandlerAsAHostedService<>).MakeGenericType(tHandler);
 
-        Func<IServiceProvider, IHostedService> implementationFactory =
-            serviceProvider => (IHostedService)ActivatorUtilities.CreateInstance(serviceProvider, handlerAsAHostedServiceTHandler, stepName);
+        IHostedService implementationFactory(IServiceProvider serviceProvider) => (IHostedService)ActivatorUtilities.CreateInstance(serviceProvider, handlerAsAHostedServiceTHandler, stepName);
```
Comment (dluc) [inline service/Core/Handlers/DependencyInjection.cs:106]: what changed here?

Comment (alkampfergit) [reply service/Core/Handlers/DependencyInjection.cs:106]: Created a private function, old code does not compile in my machine so I applied the refactoring to have it compile.

File: tools/InteractiveSetup/Main.cs (hunk 1 above)
Comment (alkampfergit) [reply tools/InteractiveSetup/Main.cs:625]: What I do not understand is:

I started the wizard, I select to use simple storage, or simple queue, the wizard ask me the path on disk, then the wizard write that path on the configuration, but since the default is Volatile, the disk was never used. Then the user look at the configuration file and see that the file correctly contains the path, but nevertheless nothing get written. I find it confusing.

What is the purpose of asking the path to the user if then the configuration is Volatile? 

A better option would be to ask the user if they want to use in-memory (volatile) or disk.

File: service/Core/Handlers/DependencyInjection.cs (hunk 2 above)
Comment (marcominerva) [reply service/Core/Handlers/DependencyInjection.cs:106]: @alkampfergit see also this: https://github.com/microsoft/kernel-memory/pull/362#discussion_r1523409039

Comment (alkampfergit) [reply service/Core/Handlers/DependencyInjection.cs]: Removed the modified file, after all there is no correlation with this PR it helps reduce the scope.

File: tools/InteractiveSetup/Main.cs (hunk 1 above)
Comment (dluc) [reply tools/InteractiveSetup/Main.cs]: the setup wizard doesn't say path "on disk" :-)

> Directory where to store queue messages [current: _tmp/queues]:
> Directory where to store files [current: _tmp/files]:

SimpleStorage, SimpleQueue and SimpleVector internally use a filesystem that supports directories. The FS can be Persistent of Volatile, in both cases it uses "directories".  

By default it's a volatile FS, and the setup wizard doesn't ask, which is the part that could be improved.

Comment (dluc) [reply tools/InteractiveSetup/Main.cs]: > I've made a change: Now the user can specify an empty path to explicitly choose Volatile, but if they specify a valid path, Disk configuration is used.

This won't work, even if volatile the path cannot be empty. As I mentioned, we won't change the default, but we can improve the wizard to ask.

**Review by dluc — CHANGES_REQUESTED** [review]
Both persistent and volatile storage use directories. Please undo changes to Main.cs, or extend the wizard to ask the storage type.

File: tools/InteractiveSetup/Main.cs (hunk 1 above)
Comment (alkampfergit) [reply tools/InteractiveSetup/Main.cs]: Ok understood, if you want I can change the wizard to explicitly ask if the storage must be volatile or disk, it should be a quick and simple change.

I noticed now that the question is about path and did not tell Path on disk :D :D :), but nevertheless path lead to think that this will be saved on disk. An explicit question about

Do you want to persist on disk or you want it to be volatile? 

Should suffice

Comment (dluc) [reply tools/InteractiveSetup/Main.cs]: your call, if you have time to add the new question it would certainly be great :-)

File: tools/InteractiveSetup/Main.cs
[the remark this answers is not in the document]
Comment (dluc) [reply tools/InteractiveSetup/Main.cs:1]: I'd like to merge the fix on AppSettings.cs, so I will roll back these changes and merge. If you'd like to extend the config wizard asking for storage type we can do that on a separate PR. Thanks

File: tools/InteractiveSetup/Main.cs [hunk 3]
```diff
@@ -626,9 +626,12 @@ private static void SimpleQueuesSetup()
             };
         }
 
+        var queueFolderOnDisk = SetupUI.AskOpenQuestion("Directory where to store queue messages, empty to use in memory volatile queue", "", optional: true);
+
         AppSettings.Change(x => x.Services[ServiceName] = new Dictionary<string, object>
         {
-            { "Directory", SetupUI.AskOpenQuestion("Directory where to store queue messages", config["Directory"].ToString()) }
+            { "StorageType", string.IsNullOrEmpty(queueFolderOnDisk) ? "Volatile" : "Disk" },
+            { "Directory", queueFolderOnDisk }
```
Comment (dluc) [inline tools/InteractiveSetup/Main.cs:634]:
```suggestion
            { "Directory", SetupUI.AskOpenQuestion("Directory where to store queue messages", config["Directory"].ToString()) }
```

File: tools/InteractiveSetup/Main.cs [hunk 4]
```diff
@@ -626,9 +626,12 @@ private static void SimpleQueuesSetup()
             };
         }
 
+        var queueFolderOnDisk = SetupUI.AskOpenQuestion("Directory where to store queue messages, empty to use in memory volatile queue", "", optional: true);
+
```
Comment (dluc) [inline tools/InteractiveSetup/Main.cs:630]:
```suggestion
```

File: tools/InteractiveSetup/Main.cs [hunk 5]
```diff
@@ -732,9 +735,12 @@ private static void SimpleFileStorageSetup()
             };
         }
 
+        var queueFolderOnDisk = SetupUI.AskOpenQuestion("Directory where to store files, empty to use in memory volatile storage", "", optional: true);
+
```
Comment (dluc) [inline tools/InteractiveSetup/Main.cs:739]:
```suggestion
```

File: tools/InteractiveSetup/Main.cs [hunk 6]
```diff
@@ -860,9 +866,12 @@ private static void SimpleVectorDbSetup(bool force = false)
             };
         }
 
+        var queueFolderOnDisk = SetupUI.AskOpenQuestion("Directory where to store vectors, empty to use in memory volatile memory", "", optional: true);
+
```
Comment (dluc) [inline tools/InteractiveSetup/Main.cs:870]:
```suggestion
```

File: tools/InteractiveSetup/Main.cs [hunk 7]
```diff
@@ -732,9 +735,12 @@ private static void SimpleFileStorageSetup()
             };
         }
 
+        var queueFolderOnDisk = SetupUI.AskOpenQuestion("Directory where to store files, empty to use in memory volatile storage", "", optional: true);
+
         AppSettings.Change(x => x.Services[ServiceName] = new Dictionary<string, object>
         {
-            { "Directory", SetupUI.AskOpenQuestion("Directory where to store files", config["Directory"].ToString()) }
+            { "StorageType", string.IsNullOrEmpty(queueFolderOnDisk) ? "Volatile" : "Disk" },
+            { "Directory", queueFolderOnDisk }
```
Comment (dluc) [inline tools/InteractiveSetup/Main.cs:743]:
```suggestion
            { "Directory", SetupUI.AskOpenQuestion("Directory where to store files", config["Directory"].ToString()) }
```

File: tools/InteractiveSetup/Main.cs [hunk 8]
```diff
@@ -860,9 +866,12 @@ private static void SimpleVectorDbSetup(bool force = false)
             };
         }
 
+        var queueFolderOnDisk = SetupUI.AskOpenQuestion("Directory where to store vectors, empty to use in memory volatile memory", "", optional: true);
+
         AppSettings.Change(x => x.Services[ServiceName] = new Dictionary<string, object>
         {
-            { "Directory", SetupUI.AskOpenQuestion("Directory where to store vectors", config["Directory"].ToString()) }
+            { "StorageType", string.IsNullOrEmpty(queueFolderOnDisk) ? "Volatile" : "Disk" },
+            { "Directory", queueFolderOnDisk }
```
Comment (dluc) [inline tools/InteractiveSetup/Main.cs:874]:
```suggestion
            { "Directory", SetupUI.AskOpenQuestion("Directory where to store vectors", config["Directory"].ToString()) }
```

**Review by dluc — CHANGES_REQUESTED** [review]
